services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-7&*zy=hp%(y(+e$%r_2qs5=0+_i89^lc#mkz3btfwrde7=d9-="
      - "DJANGO_DEBUG=True"
      - "DJANGO_EMAIL_HOST="
      - "DJANGO_EMAIL_HOST_USER="
      - "DJANGO_EMAIL_HOST_PASSWORD="
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: